export default [
    "keep going",
    "dream big",
    "kindness",
    "stay humble",
    "stay strong",
    "keep smiling",
    "brave",
    "grateful",
    "work hard",
    "believe",
    "keep learning",
    "honest",
    "Hope",
    "embrace",
].map(quote => quote.replace(/[.,'\/#!$%\^&\*;:{}=\-_`~()]/g,""));