export default [
    "keep going",
    "dream big",
    "kindness",
    "stay humble",
    "stay strong",
    "keep smiling",
    "laughter",
    "grateful",
    "work hard",
    "believe",
    "keep learning",
    "harmony",
    "joyful heart",
    "sunny day",
].map(quote => quote.replace(/[.,'\/#!$%\^&\*;:{}=\-_`~()]/g,""));